[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"
name = "regen"
publish = false
version = "0.0.0"

[dependencies]
anyhow = "1.0.26"
heck = "0.3.1"
proc-macro2 = "1.0.8"
quote = "1.0.2"
svd-parser = "0.9.0"
syn = "1.0.14"
